-- Esquema propio del core. El esquema public lo escribe el batch (semanas 1-3) y el core solo lo lee.
-- Aqui viven los datos que los canales en linea SI modifican: saldos disponibles, tarjetas y operaciones.
-- SQL portable entre PostgreSQL 17 y H2 en modo PostgreSQL (las pruebas corren sobre H2).

create table core.cliente (
    id         bigint generated by default as identity primary key,
    nombre     varchar(120) not null unique,
    creado_en  timestamp    not null
);

create table core.usuario (
    id                bigint generated by default as identity primary key,
    usuario           varchar(60)  not null unique,
    password_hash     varchar(100) not null,
    rol               varchar(20)  not null check (rol in ('CLIENTE', 'EJECUTIVO')),
    cliente_id        bigint null references core.cliente (id),
    activo            boolean      not null,
    intentos_fallidos int          not null default 0,
    bloqueado_hasta   timestamp    null
);

-- id = cuenta_id del sistema legacy. cliente_id null cuando el titular llego como "Sin identificar".
create table core.cuenta (
    id                      bigint primary key,
    cliente_id              bigint null references core.cliente (id),
    titular                 varchar(120)  not null,
    tipo                    varchar(20)   not null,
    -- Red final: ninguna combinacion de errores de aplicacion puede dejar un saldo negativo.
    saldo_disponible        numeric(18, 2) not null check (saldo_disponible >= 0),
    saldo_cierre            numeric(18, 2) not null,
    tasa_mensual            numeric(8, 5)  not null,
    interes_cierre          numeric(18, 2) not null,
    anomalia                boolean        not null,
    observacion             varchar(255),
    cierre_job_execution_id bigint         not null,
    version                 bigint         not null default 0,
    actualizada_en          timestamp      not null
);

-- El numero de tarjeta nunca se guarda en claro: numero_hash = HMAC-SHA256(pepper, PAN).
create table core.tarjeta (
    id                bigint generated by default as identity primary key,
    numero_hash       varchar(64)    not null unique,
    ultimos4          varchar(4)     not null,
    cuenta_id         bigint         not null references core.cuenta (id),
    pin_hash          varchar(100)   not null,
    intentos_fallidos int            not null default 0,
    bloqueada         boolean        not null default false,
    limite_diario     numeric(18, 2) not null
);

-- unique (canal, clave_idempotencia): ultima defensa contra un retiro cobrado dos veces.
create table core.operacion (
    id                 bigint generated by default as identity primary key,
    cuenta_id          bigint         not null references core.cuenta (id),
    tarjeta_id         bigint null references core.tarjeta (id),
    tipo               varchar(20)    not null,
    canal              varchar(20)    not null,
    monto              numeric(18, 2) not null check (monto > 0),
    saldo_resultante   numeric(18, 2) not null,
    terminal_id        varchar(40),
    clave_idempotencia varchar(80)    not null,
    huella_solicitud   varchar(64)    not null,
    creada_en          timestamp      not null,
    constraint uk_operacion_canal_clave unique (canal, clave_idempotencia)
);

create index idx_operacion_tarjeta_fecha on core.operacion (tarjeta_id, creada_en);
create index idx_operacion_cuenta_fecha on core.operacion (cuenta_id, creada_en);
