-- Semana 7: el core como participante de la saga de transferencias (coreografia sobre Kafka).
-- SQL portable entre PostgreSQL 17 y H2 en modo PostgreSQL.

-- Una fila por transferencia que llego al core. El monto queda retenido en la cuenta de origen (saldo_disponible ya
-- descontado) mientras antifraude decide; al aprobar se acredita el destino, al rechazar se devuelve (compensacion).
-- Sin FK a cuenta: tambien se registran las rechazadas por cuenta inexistente.
create table core.reserva (
    transferencia_id varchar(36)    primary key,
    cliente_id       bigint         not null,
    cuenta_origen    bigint         not null,
    cuenta_destino   bigint         not null,
    monto            numeric(18, 2) not null check (monto > 0),
    estado           varchar(20)    not null check (estado in ('RESERVADA', 'RECHAZADA', 'CONFIRMADA', 'LIBERADA')),
    motivo           varchar(40),
    creada_en        timestamp      not null,
    actualizada_en   timestamp      not null
);

-- Consumidor idempotente: Kafka entrega al menos una vez; un evento ya procesado se ignora.
create table core.evento_procesado (
    evento_id    varchar(36) primary key,
    tipo         varchar(40) not null,
    procesado_en timestamp   not null
);

-- Transactional outbox: el evento se guarda en la misma transaccion que el cambio de saldo y un publicador lo envia a
-- Kafka despues. Asi nunca queda un saldo cambiado sin su evento, ni un evento de un cambio que se revirtio.
create table core.outbox (
    id           bigint generated by default as identity primary key,
    evento_id    varchar(36)  not null unique,
    topico       varchar(80)  not null,
    clave        varchar(40)  not null,
    tipo         varchar(40)  not null,
    payload      varchar(2000) not null,
    creado_en    timestamp    not null,
    publicado_en timestamp
);

create index idx_outbox_pendiente on core.outbox (publicado_en, id);
