-- Esquema propio de transferencias-service: nadie mas escribe aqui. SQL portable entre PostgreSQL 17 y H2.

-- Estado de cada transferencia vista por el cliente. La saga la mueve: PENDIENTE -> FONDOS_RESERVADOS ->
-- COMPLETADA | RECHAZADA. unique (cliente, clave): un reintento del cliente con la misma clave no crea otra.
create table transferencias.transferencia (
    id                 varchar(36)    primary key,
    cliente_id         bigint         not null,
    usuario_id         bigint         not null,
    cuenta_origen      bigint         not null,
    cuenta_destino     bigint         not null,
    monto              numeric(18, 2) not null check (monto > 0),
    estado             varchar(20)    not null check (estado in ('PENDIENTE', 'FONDOS_RESERVADOS', 'COMPLETADA', 'RECHAZADA')),
    motivo             varchar(40),
    validacion         varchar(10)    not null check (validacion in ('PREVIA', 'DIFERIDA')),
    clave_idempotencia varchar(80)    not null,
    creada_en          timestamp      not null,
    actualizada_en     timestamp      not null,
    constraint uk_transferencia_cliente_clave unique (cliente_id, clave_idempotencia)
);

-- Historial: cada evento de la saga que toco la transferencia, en orden. Es la traza que ve el cliente.
create table transferencias.historial (
    id               bigint generated by default as identity primary key,
    transferencia_id varchar(36) not null references transferencias.transferencia (id),
    evento           varchar(40) not null,
    detalle          varchar(120),
    ocurrido_en      timestamp   not null
);

create index idx_historial_transferencia on transferencias.historial (transferencia_id, id);

create table transferencias.evento_procesado (
    evento_id    varchar(36) primary key,
    tipo         varchar(40) not null,
    procesado_en timestamp   not null
);

-- Transactional outbox (igual que en el core): la solicitud y su evento se guardan juntos.
create table transferencias.outbox (
    id           bigint generated by default as identity primary key,
    evento_id    varchar(36)   not null unique,
    topico       varchar(80)   not null,
    clave        varchar(40)   not null,
    tipo         varchar(40)   not null,
    payload      varchar(2000) not null,
    creado_en    timestamp     not null,
    publicado_en timestamp
);

create index idx_outbox_pendiente on transferencias.outbox (publicado_en, id);
